### ISSUE TITLE
Multiple working directory

### ISSUE THREAD

**Issue by tcyuan373** [Islam0mar/CL-CXX-JIT#2]
Hello, I am curious whether its possible to setup multiple working directory instead of just "/tmp/", because there are multiple hpp header files spread across the system.  Or the only option at the moment is collecting them and all put in /tmp/ directory?

**Comment by Islam0mar** [comment]
Hi,
- Append ` -I/your/path` to `*cxx-compiler-flags*` --be careful about spaces-- .
- Then Append `-l...` to `*cxx-compiler-link-libs*` --may use `-L` for files spread across the system--.

`*cxx-compiler-flags*` defaults to `-std=c++17 -Wall -Wextra -I/usr/include/eigen3`. see [Flags Table](https://github.com/Islam0mar/CL-CXX-JIT#prerequisites) for details.

Kindly feel free to ask for improvements.

**Comment by tcyuan373** [comment]
Another issue is that, no matter how I update the ld linker for the system and *cxx-compiler-link-libs* and *cxx-compiler-flags*, it seems cxx-jit cannot find the corresponding libraries with -lmylib flag, I was wondering if this is the problem on my side or the problem with cxx-jit itself, would you mind helping me with this?  Your help is greatly appreciated!

**Comment by Islam0mar** [comment]
The error message would help,so kindly post it.

Assuming your lib is named `libmylib.so`, you have to add ` -L/path/to/dir ` as well as ` -lmylib `. See `-l` and `-L` compiler flags for more info.

Or add your lib full path ` /path/to/libmylib.so ` as a flag.

**Comment by tcyuan373** [comment]
That is exactly what I did, I added -L/path/to/mylib, and -lmylib, and update ld, then sudo ldconfig and also add /path/to/libmylib.so, so I had this question.

The error message would be:
/tmp/plugin.cpp:1:10: fatal error: mylib/foo.h: no such file or directory

**Comment by tcyuan373** [comment]
> The error message would help,so kindly post it.
> 
> Assuming your lib is named `libmylib.so`, you have to add `-L/path/to/dir` as well as `-lmylib`. See `-l` and `-L` compiler flags for more info.
> 
> Or add your lib full path `/path/to/libmylib.so` as a flag.

Sorry to bother again, did you have the chance to check this issue yet

**Comment by Islam0mar** [comment]
`/tmp/plugin.cpp:1:10: fatal error: mylib/foo.h: no such file or directory` is an error for header file inclusion. `-I`

let the header file full path is `/home/me/code/mylib/foo.h`, you have to add `-I/home/me/code` to `*cxx-compiler-flags*`, so compiler would find `#include "mylib/foo.h"`.

**Comment by tcyuan373** [comment]
> `/tmp/plugin.cpp:1:10: fatal error: mylib/foo.h: no such file or directory` is an error for header file inclusion. `-I`
> 
> let the header file full path is `/home/me/code/mylib/foo.h`, you have to add `-I/home/me/code` to `*cxx-compiler-flags*`, so compiler would find `#include "mylib/foo.h"`.

That is exactly what I did, but the problem persist.  Would you mind checking on your side, for a project installed using cmake, to be imported using cxx-jit

**Comment by Islam0mar** [comment]
I need some context to reproduce, so kindly provide a complete command like the following:
```lisp
CL-USER> (cxx-jit:from '("asd.h") 'import nil )

"/usr/bin/g++ -shared -fPIC -Wl,--no-undefined -Wl,--no-allow-shlib-undefined -std=c++17 -Wall -Wextra -I/usr/include/eigen3 /tmp/plugin.cpp -o /tmp/plugin.so -lm" 
"/tmp/plugin.cpp:1:10: fatal error: asd.h: No such file or directory" 
"    1 | #include \"asd.h\"" 
"      |          ^~~~~~~" 
"compilation terminated." 
NIL
CL-USER> 
```
Plus your project directory tree. minimal complete example would also help.

I have no issue using the lib.

**Comment by tcyuan373** [comment]
> I need some context to reproduce, so kindly provide a complete command like the following:
> 
> ```lisp
> CL-USER> (cxx-jit:from '("asd.h") 'import nil )
> 
> "/usr/bin/g++ -shared -fPIC -Wl,--no-undefined -Wl,--no-allow-shlib-undefined -std=c++17 -Wall -Wextra -I/usr/include/eigen3 /tmp/plugin.cpp -o /tmp/plugin.so -lm" 
> "/tmp/plugin.cpp:1:10: fatal error: asd.h: No such file or directory" 
> "    1 | #include \"asd.h\"" 
> "      |          ^~~~~~~" 
> "compilation terminated." 
> NIL
> CL-USER> 
> ```
> 
> Plus your project directory tree. minimal complete example would also help.
> 
> I have no issue using the lib.

Do you mind if we discuss through email

**Comment by Islam0mar** [comment]
Nope.

`io1131@fayoum.edu.eg`
