### ISSUE TITLE
define types in an variable or parameter

### ISSUE THREAD

**Issue by leosongwei** [Islam0mar/CL-CXX-JIT#3]
Hi, I find this package very handy, but I got an issue with unregistered types.

Currently all return types is registered in the `cffi-type` function in the `cxx-jit.lisp`. But whenever it faces an unregistered type, it will say something like `No Known conversion for type "long unsigned int". default to pointer`. Can you move the type registration into an variable, so users can extend it?

**Comment by Islam0mar** [comment]
hello @leosongwei,

Do you need class like type or C++ integral types?

you could static cast function to match the corresponding [types](https://github.com/Islam0mar/CL-CXX-JIT/blob/master/src/cxx-jit.lisp#L40), I may guess that you are using windows! I will revisit `cffi-type` and may add something to match a custom string.

sorry for late response, I have a problem with github notifications.

**Comment by Islam0mar** [comment]
Is `(push (cons "long unsigned int" :ulong) cxx-jit:*cxx-type-name-to-cffi-type-symbol-alist*)` fine ?

**Comment by leosongwei** [comment]
that will be nice!

**Comment by Islam0mar** [comment]
You could try it, and let me know, if it's enough.
